export const themeLantersMarkers = [
  {
    id: '01',
    title: '旺進來',
    engTitle: 'Bringing Prosperity to You',
    artist: '都市藝術工作室',
    engArtist: 'Urban Art Studio',
    description: '今年是農曆生肖的狗年，都市藝術工作室特地於當地具有代表性的橋南老街入口處，設置造型可愛的燈箱作品〈旺進來〉，除了祝福每位造訪此地的觀眾都能新年行大運之外，熱情歡迎的狗兒也點出了這次的主題「相約」：期待與您於此相會。',
    engDescription: '2018 is the year of the Dog according to the Chinese zodiac. The Urban Art Studio specifically designed an adorable light box titled Bringing Prosperity to You and installed it at the entrance of Ciaonan Street, an iconic site within the Yuejin Harbor area. In addition to wishing every visitor great fortune, this hospitable dog reflects the theme of this year—“appointment.” We look forward to meeting you here.',
    coordinate: {
      latitude: 23.315172,
      longitude: 120.267964
    },
    image: require('../assets/images/01.png'),
  },
  {
    id: '02',
    title: '光動能',
    engTitle: 'Photo-dynamism',
    artist: '友意國際',
    engArtist: 'Unison Art Association',
    description: '時間如同河流，不斷沖刷際遇的同時，也在積累豐富的記憶。擁有多媒體影像設計背景的團隊「友意國際」，在〈光動能〉中藉由光影交錯的變化，將抽象的時光具體為視覺與影像的互動裝置，透過觀眾的親身介入，去改變和體會作品所呈現出的不同效果，除了拉近人與人的距離外，也創造出人與藝術交會的美麗風景。',
    engDescription: 'Time elapses as if it is a flowing river. In the course of time, we not only experience vicissitudes of life but also accumulate a wealth of memories. With a background in multimedia image design, the Unison Art Association transformed abstract time into a tangible imagery interactive installation by weaving light with shadow in Photo-dynamism. The visitors will change and experience the diverse effects produced by this installation in an immersive fashion, which not only shortens interpersonal distance but also creates a charming scene where people meet the arts.',
    coordinate: {
      latitude: 23.317098,
      longitude: 120.266699
    },
    image: require('../assets/images/02.png'),
  },
  {
    id: '03',
    title: '光輝興隆',
    engTitle: 'The Brilliance',
    artist: '沁弦國際設計',
    engArtist: 'CosmoC design,Ltd.',
    description: '興隆橋上的燈光裝置，在夜色中迎風搖曳著，光輝的律動像是一首悠揚的樂曲迎接著造訪此地的人們，更映畫出橋南老街的美麗景致與新興未來的展望。',
    engDescription: 'The Brilliance of the lighting installation at Xinglong Bridge swaying at night like the rhythm of a melodious song greets people who visit here as well as reflecting the beautiful scenery of South-bridge Old Street and the emerging prospects of the future.',
    coordinate: {
      latitude:  23.315172,
      longitude: 120.267964
    },
    image: require('../assets/images/03.png'),
  },
  {
    id: '04',
    title: '月光光果實',
    engTitle: 'Moonlight Fruits',
    artist: '易冶設計（鄞宗道、賴彥睿、何曉瑜、龔柏閔、丁元鈞）',
    engArtist: 'YiYe design (Yin Tsung Tao, Lai Yan Ruei, Ho Hsiao Yu, Kung Po Min, Ding Yuan Ju)',
    description: '月光光果實，吸收月光與月津港水面蒸霞之氣孕育而成。在節氣之時，結實累累、藍綠相間、光滑隱透於表面，散發瑩火於夜間，隨月津水岸錯落而生，隨風搖擺，隨水浮動。「易冶設計」在水域邊，設置了多件造型和色彩各異的燈光裝置，這些耐人尋味的奇特造型，在夜色中兀自發光，彷彿是來自其他星球的果實——藝術家的豐富想像力，與月津港特有的在地景致並置融合，共同創造出全新的空間感受。',
    engDescription: 'Moonlight Fruits are cultivated collectively by moonlight and the mist over the Yuejin Harbor. At the harvest season, the blue and green fruits ripen in clusters, coated with glassy surfaces and emitting fluorescent light during the night. They lay strewn along the waterfront of the Yuejin Harbor, bending in the wind and drifting with water. YiYe Design placed several lighting installations different in shape and color. Their peculiar, thought-provoking shapes glow in the dim light of night, making themselves nothing short of fruits from other planets. The artist’s fertile imagination harmoniously blended with the breathtaking scenery of the Yuejin Harbor, giving the visitors a new-found sense of space.',
    coordinate: {
      latitude: 23.317413,
      longitude: 120.268078
    },
    image: require('../assets/images/04.png'),
  },
  {
    id: '05',
    title: '光的織遇',
    engTitle: 'Knitting Light',
    artist: '陳冠宏x陳思涵',
    engArtist: 'Chen Kuan Hung X Chen Szu Han',
    description: '光是想像的一種代名詞。〈光的織遇〉試圖讓光編織出軌跡，舞動在曲折的橋上，讓來來往往的人們與光相會。作品利用軟性可曲折的環光燈條，編織出光的流動身影，定格出律動的光線，交織在曲橋的兩側；置身其中，能夠感受到由光的線與面所構成的光織場域。當夜色降臨，人們遠眺曲橋時，光線將織譜出視覺的浪漫樂章，與觀者相約在夢幻的光景中。',
    engDescription: 'Light is a symbol of imagination. Knitting Light is designed to weave threads of light and let them dance on the twisting bridge where the shuttling visitors encounter the dancing light. The artists used bendable light strips to create rhythmically flowing illuminations on both sides of the bridge, thereby immersing the visitors in the field comprising lines and planes of light. When the visitors gaze into the twisting bridge at a distance in the twilight, they will come across the radiance of the fantastic light-scape and become enchanted by the romantic, mesmeric visual effect of this work.',
    coordinate: {
      latitude: 23.317502,
      longitude: 120.268255
    },
    image: require('../assets/images/05.png'),
  },
  {
    id: '06',
    title: 'I',
    engTitle: '',
    artist: '何采柔',
    engArtist: 'Ho Joyce',
    description: '擅長揉合劇場設計和視覺呈現的藝術家，在靠近月津港曲橋的樹叢間，創作了「I」。顧名思義，作品的造型本身就像是英文大寫字母的I——在白天，它就是一個單純兀立在森林裡的物件；然而到了夜晚，被點亮的I就像是推開門時從門縫中透出來的光線，成為一處帶有超現實意味的空間，為夜景開啟了一扇想像之門。「I」邀請每位觀眾在此駐足停留，品味那些位於可見與不可見之間的迷離詩意。',
    engDescription: 'Being skilled at blending theatrical design with visual presentation, Joyce Ho installed the work I in the bushes near the twisting bridge of Yuejin Harbor. By definition, this work was made in the shape of the capital letter “I” In the daytime, it is simply an object standing upright and motionless in the bushes. When the night falls, the lighted piece bears more than a passing resemblance to the light escaping through the narrow opening between a door and its frame, making its immediate vicinity a marvelous space with a touch of surrealism, which unlocks a door into imagination in the nightscape. The artist cordially invites each visitor to stop for this piece of work and savor the psychedelic, poetic quality amidst the visible and the invisible.',
    coordinate: {
      latitude: 23.317325,
      longitude: 120.268507
    },
    image: require('../assets/images/06.png'),
  },
  {
    id: '07',
    title: '光雲',
    engTitle: 'Light Cloud',
    artist: '蘇小夢',
    engArtist: 'Su Xiao Meng',
    description: '長期專注於金工創作的藝術家蘇小夢，以環保再生概念為基礎，利用纏繞的塑料長管和燈光，製作成漂浮在水面的白色造型——有如雲朵或花卉的〈光雲〉，在靠近曲橋的河中映射出自己的倒影，鏡花水月的詩意風景，讓每位相約在此的舊識，或是相逢邂逅的新知，都能眺望到這片浪漫美麗的光影風景，並在記憶中留下深刻的視覺印象。',
    engDescription: 'Drawing on the concepts of environmental protection and sustainability, Xiao-Meng Su, an artist who has long dedicated to metalwork, made clever use of intertwined plastic tubes and light to create Light Cloud, a cloud- or flower-like white installation floating on the surface of the water. Its reflection appears on the calm waters near the twisting bridge. Such an unrealistic rosy view allows the visitors, be they old friends who made appointments to meet here or new acquaintances who have chance encounters, to take in this romantic, gorgeous scenery from an elevated position and ergo to gain a strong visual impression as to the charm of this work.',
    coordinate: {
      latitude: 23.317823,
      longitude: 120.268432
    },
    image: require('../assets/images/07.png'),
  },
  {
    id: '08',
    title: '候鳥：文化之橋',
    engTitle: 'Migratory Bird: Bridging Cultures',
    artist: '森岡 厚次、中川 明衣、戎 里央、宮田 真奈、稲田 光佑',
    engArtist: 'MORIOKA Koji, NAKAGAWA Mei, EBISU Rio, MIYATA Mana, INADA Kosuke',
    description: '候鳥根據季節飛翔，在每年的同一時刻造訪同樣的地方；鳥類藉此尋找新的資源和環境，而人們亦同樣藉由旅行激發新的靈感與創意；藝術家採用了質地溫潤的木材、紙質和燈具，在曲橋周邊製作了侯鳥造型的裝置：張開翅膀的鳥兒，彷彿是將要振翅而起，也像是正要降落歸巢。透過候鳥的遷徙和返鄉，來自日本的森岡厚次在作品中思考的是旅行與歸鄉的意義——是遊子對於故鄉的約定，也是個人與自己內在的探索之旅。',
    engDescription: 'Migratory birds migrate annually according to seasons and visit the same place at a specific time, so as to find new resources and congenial environments. People also seek creative inspiration through travel. Employing approachable materials such as timber, paper and lamp, the artist created a migratory bird-shaped installation and installed it near the twisting bridge. The wing-unfurling bird seems about to take off as well as to land on its nest. Drawing on the implication of this migratory bird, Japanese artist Koji Morioka reflects on the meaning of traveling and homecoming—a promise made by travelers to their hometowns as well as his inner spiritual journey into the unknown.',
    coordinate: {
      latitude: 23.317798,
      longitude: 120.268593
    },
    image: require('../assets/images/08.png'),
  },
  {
    id: '09',
    title: '吻',
    engTitle: 'Kiss',
    artist: 'Hong Sang Sik',
    engArtist: '',
    description: '親吻是人類特有的表達愛意的方法，無論是朋友、親人、伴侶或是愛人，各種形式的親吻將人與人之間相會時的千言萬語，化作無聲卻具體的行動。來自韓國的Sang sik hong，以燈光和吸管創造出嘴唇的圖樣，象徵著人的慾望；藝術家認為，慾望和權力是強大的，然而吸管卻是物質結構十分薄弱的材質，它可以被大量製造，能夠隨手取得也經常被隨意丟棄。用吸管形成的吻，可能是永摯不渝的愛戀，也可能只是稍縱即逝的邂逅——回應的是人與人交會時的種種情節。',
    engDescription: 'A kiss is synonymous with love. Kisses turn the countless words that people (be they friends, families, partners or lovers) have to say when they meet into silent yet passionate actions. South Korean artist Sang sik hong created the pattern of lips with light and straws, and used it as a metaphor to represent human desires. The artist believes that desires and power are forceful, while straws are weak in physical structure. The latter can be produced massively and are therefore easily available and disposable. The kiss made from straws could imply undying love or simply a brief encounter, which reflects various and sundry episodes of interpersonal relationships.',
    coordinate: {
      latitude: 23.317752,
      longitude: 120.268755
    },
    image: require('../assets/images/09.png'),
  },
  {
    id: '10',
    title: '枯山水',
    engTitle: 'Japanese Rock Garden',
    artist: '森岡 厚次、林 里奈、林 香奈、辻 修也、村上 華奈子、鬼川 いおり、古沢 樹',
    engArtist: 'MORIOKA Koji, HAYASHI  Rina, HAYASHI Kana, TSUJI Shuya, MURAKAMI Kanako, ONIKAWA Iori, FURUSAWA Itsuki',
    description: '日本具有代表性的園林形式「枯山水」，以單純的細沙和石塊，在極簡的形式中創造出深邃寧靜的美感。來自京都的藝術家森岡厚次，此次特別受邀參與燈節的交流創作，他特別按照月津港的地景環境，在當地量身打造出枯山水的別緻意象，與環境本身所具有的水岸風情相互呼應，交會出具有台灣與日本特質的嶄新場域。',
    engDescription: 'Japanese rock garden is an iconic Japanese landscaping paved with fine sand and rocks, which creates profound and tranquil aesthetic appeal in a minimalist form. Being invited to present his work at the lantern festival, Koji Morioka, a Japanese artist from Kyoto, customized a delicate Japanese rock garden that blends in with the landscape of Yuejin Harbor. This work perfectly echoes the local waterfront scenery and opens up a brand new space bearing the characteristic signatures of both Taiwan and Japan.',
    coordinate: {
      latitude: 23.317466,
      longitude: 120.268632
    },
    image: require('../assets/images/10.png'),
  },
  {
    id: '11',
    title: '合 橋 雨 然 偶',
    engTitle: 'Happenstance',
    artist: '南藝大建築所、場域‧結構‧行動組',
    engArtist: 'Tainan National University of the Arts graduate institute of architecture, Field & Action Studio',
    description: '擅長利用原有空間，透過裝置結構改變原有環境屬性的「場域‧結構‧行動組」，將在慈德禪寺前的廣場空地，利用植物染布幔、燈光和輕型結構，打造出有如迷宮般的場域——人們得以自由地遊走在飽滿吸附光線的布幔森林中，透光的布料將著戶外的風而輕盈飄動，觀眾將遊繞穿梭在沒有明確界線的狀態裡，彼此漫遊、交錯、驚鴻一瞥或擦身而過。宛如劇場般的空間，是人群之中相遇交會的縮影，折射出各種人際關係的可能。',
    engDescription: 'Being skilled at altering a place’s original attributes with installations and structures, the “Field‧Structure‧Action Collective” transformed the square in front of the Cide Temple into a labyrinth with pieces of plant-dyed curtains, lights, and lithe structures. The visitors are allowed to freely roam the curtain forest saturated by light. The translucent fabrics flutter with the wind outdoors, immersing the visitors in an ambiguously demarcated space where they drift, catch a glimpse of or brush past one another. The theater-like space is a microcosm of the society that refracts possible interpersonal relationship of all stripes.',
    coordinate: {
      latitude: 23.317363,
      longitude: 120.268788
    },
    image: require('../assets/images/11.png'),
  },
  {
    id: '12',
    title: '植光計劃－川',
    engTitle: 'Light Planting Project—Creek',
    artist: '沃手工作',
    engArtist: 'Winnowork',
    description: '在曲橋的水岸，藝術家團隊設置了約80支、高約100公分的光球裝置，彷彿植物蔓生一般，散布在河畔。這些花苞狀的植被，將在晚間逸散出有如自然呼吸般的韻律光芒，點綴著月津港的黑夜，遠觀有如閃爍的晶瑩光海；然而，當觀眾靠近或觸碰，花朵則會隨之綻放——繽紛的虹光之花因為人的溫度而盛開，一期一會，成為燈節中情意深重的浪漫風景。',
    engDescription: 'The team installed around 80 light-ball installations along the waterfront near the twisting bridge. They ramble over the riverside like plants and each of them is 100 centimeters in height. The bud-shaped vegetation exudes a rhythmic aura in the dim light of night, serving as the perfect foil for the nighttime of Yuejin Harbor. Distance lends enchantment to the view of a sea of twinkling light. These flower buds will open and wear iridescent colors when they sense the body temperature of the visitors who approach or touch them. The romantic scene conveys the idea of “one encounter in a lifetime,” a loving display of deep affection during the lantern festival.',
    coordinate: {
      latitude: 23.317311,
      longitude: 120.269027
    },
    image: require('../assets/images/12.png'),
  },
  {
    id: '13',
    title: '光間帶',
    engTitle: 'Intertidal Zone',
    artist: '有用主張',
    engArtist: 'UxU Design Studio',
    description: '光是一種帶著無限想像的媒介。〈光間帶〉這件作品試圖讓光呈現無重力的漂浮狀態，形構出一個融合速度、氛圍與空間維度的場域。在月津港畔的帶狀樹林間，人們穿梭其中偶然相遇與相離；作品試圖在林間設置大量的流星燈，以水平的姿態朝同一個方向飛去，光群此起彼落的閃爍輝映，猶如具生命般交匯出一條光的潮間帶，希冀創造出奇幻無常的光域，引領人們遊走其中邂逅與體驗，展開一場別開生面的與光之約。',
    engDescription: 'Light is a medium of infinite imagination. The work Inter-light Zone is designed to exhibit light in a gravity-free state and to create a realm comprising the dimensions of speed, atmosphere and space. People encounter and leave each other in the bushes along the Yuejin Harbor. The team ergo installed a large number of LED meteor light tubes that stretch horizontally in the same direction, creating a lively intertidal zone with rhythmically twinkling lights that make each shine more brilliantly in the others’ company. With this work, the team expects to construct a fantastic, mercurial light-scape around which the visitors can wander and have a breathtaking encounter with the enchanting light.',
    coordinate: {
      latitude: 23.317444,
      longitude: 120.269541
    },
    image: require('../assets/images/13.png'),
  },
  {
    id: '14',
    title: '日月虹光',
    engTitle: 'Colors of the Spectrum',
    artist: '沃手工作',
    engArtist: 'winnowork',
    description: '對於「沃手工作」的藝術家團隊來說，橋樑帶有跨越和串接的意味，他們以燈管、金屬結構、鋼索和燈光，在水面上創造一道虹光之橋，半圓形的造型呼著日與月的光輝；而當夜晚來臨，光橋的實體也將在水面反射出相互連接的光橋虛影，象徵著對於未知的探索——古今中外、過去未來，有著彩虹色調的光橋蘊含的是生命漸進的蓬勃、衰老、新生與輪迴，也隱含著世間萬象的聚散離合。',
    engDescription: 'For the team of Winnowork, bridges imply crossing and connecting. It thus created a rainbow-like bridge on the surface of the water with fluorescent tubes, metal structures, steel wires and light. The bridge’s semicircular shape echoes the halos around the sun and the moon. When the night falls, the lighted bridge will be connected with its reflection on the calm waters, representing a voyage into the unknown. At all times and in all places, as well as in the past and future, a rainbow-like bridge not only implies the complete life cycle, but also carries the undertone of separation and reunion of everything in the world.',
    coordinate: {
      latitude: 23.317158,
      longitude: 120.269337
    },
    image: require('../assets/images/14.png'),
  },
  {
    id: '15',
    title: '釣魚小兔',
    engTitle: 'A Fishing Bunny',
    artist: '不二良',
    engArtist: 'No2Good',
    description: '動漫美學藝術家不二良，這次在2018月津港燈節推出大型作品〈釣魚小兔〉，高達五公尺的兔子公仔現身水畔垂釣，與觀眾一起相約在浪漫美好的璀璨新年。〈釣魚小兔〉來自於成語「姜太公釣魚，願者上鉤」的典故，藝術家認為，古代的姜太公離水三尺在江邊垂釣，本意不在釣魚，而在於用自己的行動引發周文王的好奇，從而達到目的——如今小兔無餌垂釣，亦非想釣水中游物，而是在意每次觀看中與人們完成的思考與對話——是直觀的感受，也是永恆的記憶。',
    engDescription: 'Ａ Fishing Rabbit is a large-scale installation created by animamix artist No2Good for the 2018 YueJin Lantern Festival. The five-meter- high rabbit doll fishes at the waterfront, meeting the visitors during the romantic and convivial Spring Festival. Inspired by the classical story of Jiang Taigong from the literature, that is, “there are always fishes willing to be caught by angler Jiang Taigong,” the artist believes that Jiang Taigong who hung a straight fishhook one meter above the water intended not so much to catch fishes as to achieve his objective by arousing the curiosity of the King Wen of Zhou. By the same token, the rabbit hanging a fishhook without bait above the water sets greater store by its meaningful dialogues with the visitors’ gazes than by catching fishes. This work not only evokes intuitive feelings, but also offers an experience the visitors will remember.',
    coordinate: {
      latitude: 23.317064,
      longitude: 120.269707
    },
    image: require('../assets/images/15.png'),
  },
  {
    id: '16',
    title: '月光',
    engTitle: 'Moonlight',
    artist: '曾瑋',
    engArtist: 'Zhen Wei',
    description: '月亮、橋洞與倒影，一直是古代文人墨客在詩畫中常見的元素——借物興嘆、以景吟詠，賦予它們豐富的詩意和內涵。在〈月光〉中，藝術家曾瑋將在水月橋的橋洞中，置入一個氣球狀的軟質發光體，就像是將原本應該在夜空中發光的月亮，巧妙地搬移到了水面之上。輕盈而具有穿透性的發光體，與堅實厚重橋墩，形成了體感上的對比，創作者以詼諧而具有創意的方式，帶給觀眾重新體驗在地環境的機會，也讓月亮、橋洞與倒影有了重新交會的可能。',
    engDescription: 'The moon, archway and reflection have been common elements in ancient poems and paintings. Ancient literati tended to express their emotions by virtue of objects and recite poetry amid scenery, rendering the objects and scenery wonderfully poetic and rich in connotation. Wei Zeng installed a balloon-like, soft and luminous body at the archway of the Shuiyue Bridge, as if the artist ingeniously moved the moon supposed to shine in the night sky onto the surface of the water. Titled Moonlight, this lithe, translucent installation contrasts sharply with the solid, heavy bridge pier in terms of mass. Adopting a way as jocular as creative, the artist not only offers the visitors exciting opportunities to rediscover the local environment, but also makes possible the reunion of the moon, archway and reflection.',
    coordinate: {
      latitude: 23.316419,
      longitude: 120.269740
    },
    image: require('../assets/images/16.png'),
  },
  {
    id: '17',
    title: '雙魚',
    engTitle: 'Pisces',
    artist: '林珮淳數位藝術實驗室（林珮淳、胡縉祥、王聖傑、吳欣怡）、王俊淵 X 共感地景創作',
    engArtist: 'Lin Pey Chwen Digital Art Lab (Lin Pey Chwen, Hu Chin Hsiang, Wang Sheng Jie, Wu Xin Yi) & Wang Chun Yuan X ArchiBlur Lab',
    description: '在中國古代，人們以鯉魚形狀的木盒作為信封，用來盛裝書信，因此信件被稱作「魚書」，而通信也稱為「魚雁往返」。藝術家援用了古詩《飲馬長城窟行》中「客從遠方來，遺我雙鯉魚。呼兒烹鯉魚，中有尺素書」的句子，將其中對於書信所蘊含的思念意涵，投注在魚的造型上——兩座如展開的魚鰭造型，結合了透明布幔，再透過變幻無窮的數位色光投射，創造出令人驚艶的抽象形體，彷彿雙魚扭身相互對話般的詩意與飄逸。\n作品浮動於水面所反射出的倒影與色光，形成虛實並置的完整圓形，在晚風中徐徐擺動，時刻變化的輕盈造型，呼應的是期待相約的浪漫懷想。',
    engDescription: 'In ancient China, people used carp-shaped wooden boxes as envelopes to hold letters. The letters were therefore called "fish books" and the correspondence "the return of the fish and geese." Adopting the idea in an ancient poem "The Great Wall of the Dying Horse" that "a dear friend visited and left me two carps; while my son was about to cook the fish, two letters were discovered inside them," the artist reflected the deep and lasting love for the beloved on the shape of fish - two spreading fins, decorated with a transparent cloth mantle along with colorful digital light projection, the sculpture represents an amazing and poetic image of two elegant fishes turning their bodies to each other to have a dialogue.\nThe reflection and light reflected by the floating sculpture form a complete circle of virtual reality and juxtaposition on the water. Slightly swinging in the evening breeze and changing its look momentarily, the light and graceful shape of the sculpture, echoes the romantic feeling of nostalgia in the air.',
    coordinate: {
      latitude: 23.316132,
      longitude: 120.270155
    },
    image: require('../assets/images/17.png'),
  },
  {
    id: '18',
    title: '光之飛熊',
    engTitle: 'Galaxy Bear',
    artist: '林建志',
    engArtist: 'Lin Chien Chih',
    description: '這件作品來自於藝術家所虛擬的故事：遠從宇宙彼端的F50星球，乘著光來到地球的是一架熊形飛行器——搭載著有如雙翅般的推進器，使它的飛行速度幾乎接近光速……光與速度一直是人們所夢想追求的極致，在農曆春假期間遠道而來的〈光之飛熊〉，象徵著人們對於期待相見的渴望。俏皮可愛的外星飛熊，替月津港燈節增添了活潑歡樂的童趣。',
    engDescription: 'Based on the fiction created by the artist, a bear-shaped spacecraft traveled through space-time to the earth from F50, a planet at the other end of the universe. The winged propeller allows the spacecraft to move near the speed of light. While light and speed have been the symbols of people’s ultimate pursuits, the work Galaxy Bear coming all the way from a remote planet during the Chinese New Year break represents people’s yearning for seeing each other. The appealingly cute alien bear also gives the Yuejin Lantern Festival a lively taste of childlike delight.',
    coordinate: {
      latitude: 23.316329,
      longitude: 120.270531
    },
    image: require('../assets/images/18.png'),
  },
  {
    id: '19',
    title: '無關',
    engTitle: 'Unrelated',
    artist: '禹禹藝術工作室',
    engArtist: 'Yu-Yu Art Studio',
    description: '生命中有很多緩慢運行的越界，在人們所認知的空間中不斷的發生和運作。在作品〈無關〉中，藝術家團隊以竹、木、鐵、鋼索和LED燈具，在水面上創造了一個具有穿透性的視覺裝置：垂直的竹片形成了虛實的空間，在自然風的吹拂下，產生了隨時變化的微妙光影交錯。創作者認為，生命本身就是一種在平行空間裡的交錯和碰撞，看似無心，實則因果牽連——那些看似無關的際遇，可能是早已注定的彼此相約。',
    engDescription: 'In our perceivable space, myriads of border-crossing actions have been taken in a creeping and constant manner. The team created Unrelated, a translucent visual installation, with bamboo, timber, iron, steel wire and LED lights, and then installed it on the surface of the water. The vertical bamboo slices interweave the real and the virtual in this space, and produce riveting intersection of shadow and light in the night breeze. As far as the team is concerned, life per se is essentially featured by a concatenation of encounters, seemingly unintentional yet in fact causally related. Those seemingly unrelated happenings could be the results of predestined appointments.',
    coordinate: {
      latitude: 23.316891,
      longitude: 120.270617
    },
    image: require('../assets/images/19.png'),
  },
  {
    id: '20',
    title: '雲中月圓',
    engTitle: 'Full Moon above the Clouds',
    artist: '陳奕彰',
    engArtist: 'Chen Yi Chang',
    description: '臺南市鹽水區為臺灣南部最古老城區，月津港也因河港彎曲有如半弧彎月而得名。〈雲中月圓〉以古城既有的美景意象為出發，援用古代東方水墨畫中描繪雲和水的流暢線條，以立體雕塑的方式呈現。期盼能夠在元宵月圓的佳節之時，創造出一幅「雲中月圓」的河港圖像，讓古今風華在此交會融合，增添月津港的夢幻浪漫的燈節氣氛。',
    engDescription: 'The Yanshuei District of Tainan has the longest history among the towns in southern Taiwan, and the Yuejin Harbor is known for its crescent shape. Treating the old town’s beautiful scenery as the point of departure, the artist appropriated the flowing lines used for depicting clouds and waters in Chinese ink paintings to create the 3-D sculpture Full Moon above the Clouds. The artist seeks to cultivate an image of the harbor in which a full moon shines above the clouds during the convivial Chinese Lantern Festival, by which the ancient and modern glories encounter and blend with each other, thereby providing a romantically mesmerizing atmosphere for the Yuejin Lantern Festival.',
    coordinate: {
      latitude: 23.317262,
      longitude: 120.270829
    },
    image: require('../assets/images/20.png'),
  },
  {
    id: '21',
    title: '相遇',
    engTitle: 'Meet',
    artist: '蘇子涵',
    engArtist: 'Su Tzu Han',
    description: '藝術家認為，「卡榫」這項生活中常見的小裝置，代表的是一種互補的狀態，而此也可以延伸至人與人的相處之道——不藉由外力去堆塑及建構，而是藉由交會得出最適切的方式。每個人都是單獨的個體，是人際關係中的零件，但當每個人彼此相連，最終將成為龐大的整體網路，形成豐富多元的社會拼圖。〈卡榫〉以幾何的裝置造型，提醒著每一個駐足觀看的人們，珍視自己獨特性的同時，也積極地與周遭的人與環境連結，發現更多饒富意趣的精彩視野。',
    engDescription: 'As far as the artist is concerned, “tenon and mortise,” a commonly seen small device, represents a state of complementation. It also applies to interpersonal relationships. In other words, the most appropriate way of interaction is not so much shaped and constructed by external forces as developed through communication. Each person is an independent individual, a part of interpersonal relationships. Once people are connected, however, they will collectively form a vast, intricate network and put together a social jigsaw puzzle having richly diverse pieces. At the time when the visitors are cherishing their respective uniqueness, the geometric shape of Tenon & Mortise calls their attention to active engagement with others and the environment, through which they can find more delightful and brilliant insights.',
    coordinate: {
      latitude: 23.317577,
      longitude: 120.270958
    },
    image: require('../assets/images/21.png'),
  },
  {
    id: '22',
    title: '星光',
    engTitle: 'Starlight',
    artist: '曾瑋',
    engArtist: 'Zhen Wei',
    description: '夜空繁星點點，人們抬頭仰望，總希望能夠伸手摘取星光，保留瞬間的美麗與想望。藝術家在氣球中設置LED燈，設置出夢幻的立體星空，隨著時間的變化，星空的顏色將會隨之轉變，成為每個人記憶中不同的星空圖譜，遼闊而深遠。',
    engDescription: 'Looking up at the stars in the night sky, we always expect to reach for them, as if we can therefore catch the ephemeral beauty and fulfill our deepest wishes. The artist simulated the fantastically starry sky by installing LED lights in the balloons. The colors of the “stars” are programmed to change with the course of time, which will inscribe a particular star atlas as vast as profound in each visitor’s mind.',
    coordinate: {
      latitude: 23.317689,
      longitude: 120.271050
    },
    image: require('../assets/images/22.png'),
  },
  {
    id: '23',
    title: '光漣漪',
    engTitle: 'Ripples of Light',
    artist: '純禾作',
    engArtist: 'Pure Do',
    description: '在暗暝的黑夜漫步河岸，你能聽見潺潺的水聲，卻看不見水流經過的波浪。在月津港河岸自行車道的水面，藝術家用動力燈光裝置〈光漣漪〉點亮夜晚的河道：8支防水的LED燈管，在河水中連接成漂浮於水上的發光虛線，隨著時間緩緩擺盪變化，彷彿在幽微中持續呼吸游泳的神祕蛟龍，光的曲線撥動出美麗的漣漪；持續改變的波紋，讓每次的觀看，都是獨一無二的經驗。',
    engDescription: 'Walking along the bank in the dark night, you can hear the sound of the babbling brook without seeing its ripples. The artist thus lights up the watercourse along the bicycle lane of the Yuejin Harbor by installing the kinetic lighting device Ripples of Light. It consists of eight interconnected waterproof LED light tubes floating on the surface of the water, forming a luminous dotted line which sways slowly with time, resembling a legendary dragon that keeps breathing and swimming in the deep darkness. The luminous curve creates engrossing and constantly changing ripples, rendering each observation and experience of this work one of a kind.',
    coordinate: {
      latitude: 23.317886,
      longitude: 120.271247
    },
    image: require('../assets/images/23.png'),
  },
  {
    id: '24',
    title: '開機',
    engTitle: 'Booting Up',
    artist: '范姜明道',
    engArtist: 'Fang Minto',
    description: '新世代的「光」讓人與人的相約，變得具有更多元的可能；透過網路與科技等媒介，使得每個人即使在巨大網際邊際中，也能夠因為「光」的啟動而互相聯結。在當代生活中，幾乎每個人隨身攜帶的手機都是一個發光體，藝術家以此現象為發想，製作了一台大型的手機裝置，向深邃的黑夜和宇宙發射訊號，串連起人和世界的各種關係。',
    engDescription: 'The “light” of the new generation opens up increasingly diverse possibilities for interpersonal encounters, and technology such as the Internet connects people with a click on the power button, even though they’ve been drawn into a vast and intricate network. As a necessary commodity for modern life, each smartphone is tantamount to a luminous object, which gave birth to the gigantic smartphone-shaped installation dedicated to sending signals into the night sky and the universe as well as to strengthening the myriads of relations between the globe and human beings living on it.',
    coordinate: {
      latitude: 23.317985,
      longitude: 120.271113
    },
    image: require('../assets/images/24.png'),
  },
]

export const openCallsMarkers = [
  {
    id: '25',
    title: '生命津春',
    engTitle: 'Spring of Life',
    school: '臺南藝術大學造形藝術研究所',
    engSchool: 'Graduate Institute of Plastic Arts, Tainan National University of the Arts',
    instructor: '詹士泰',
    engInstructor: 'Zhan Shi Tai',
    artist: '葉先傑、謝曉帆、洪敏瀚',
    engArtist: 'Ye Sian Jie, Hsieh Hsiao Fan, Hong Min Han',
    description: '正月，是萬物逐漸開始甦醒之時，金黃的春字在水面的倒映，有著「春到了」的意味，而棲居在月津的彩魚們也不定時地浮現，圍繞著春之光芒此起彼落地閃爍著，像是魚兒爭著飼料般熱鬧非凡、滿溢生機，如同了台語「呷嘎有春」（吃到有剩）的意象般，若往來的觀眾能剛好見著這充滿喜氣的景象，必然會招來來年的好福氣。',
    engDescription: 'Spring is the season when all creatures gradually return to life. We try to use the dynamic lighting in this piece to present its wonderful mood. The reflection of the golden Chinese character "春" on the water shows a good sign which is From Chinese homonym "spring is coming". And  sometimes, the colorful fishes live in Yunjin have surfaced around the spring atmosphere, which is also a symbol of good luck.  If the audience can just see this full of fantastic scenes, bound to attract good blessing in the coming year.',
    coordinate: {
      latitude: 23.19054,
      longitude: 120.16178
    },
    image: require('../assets/images/25.png'),
  },
  {
    id: '26',
    title: '月光・段',
    engTitle: 'Segmentary Moonlight',
    school: '國立臺北藝術大學新媒體藝術學系',
    engSchool: 'New Media Art, Taipei National University of the Arts',
    instructor: '蔡奇宏',
    engInstructor: 'Tsai Chi Hung',
    artist: '林瑜亮、李翎暄、劉庭均',
    engArtist: 'Lin Yu Liang, Li Ling Syuan, Liu Ting Chun',
    description: '受鹽水地區新月形狀的啟發，我們嘗試以滿月的形象與之呼應，將外型設計為滿月的數字燈光。在本次月津港燈節中，我們以對於數字流動感的基礎，構思適合的燈節作品。\n月亮是古早人們計算時間時節的準則，如今藉由電子零件將時間的概念視覺化成如七段顯示器一般的數位數字，我們將月亮與數字作結合，古今穿插，呈現月亮與數字的美。',
    engDescription: 'In this Yue Jin Lantern Festival, We intent to create a exclusively light piece base on the dynamic flow of numbers. By the inspiration of the shape of Yanshui district which is alike the shaped of new moon. We try to respond with a full moon appearance. \nThe moon is a tool of time calculating in the past. In nowadays, “time” is mostly being seen in by electronic way. We convert the electronic numbers by the 7-segment lights, and combine the moon and numbers. While the ancient and modern interspersed each other, the beauty of the number and the moon will be shown at the same time.',
    coordinate: {
      latitude: 23.19066,
      longitude: 120.16167
    },
    image: require('../assets/images/26.png'),
  },
  {
    id: '27',
    title: '綻放',
    engTitle: 'Blossom',
    school: '南華大學視覺藝術與設計系',
    engSchool: 'Graduate Institute and Department of Visual and Media Arts, Nanhua University.',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '麥子文、吳東晉、謝家欣、Wong Abandon、林羿君、黃耀正',
    engArtist: 'Mai Zi Wen, Wu Dong Jin, Xie Jia Xin, Wong Abandon, Lin Yi Jun, Huang Yue Zheng',
    description: '鹽水小鎮最出名的就是蜂炮，蜂炮點燃在空中產生的花火，成為了霎那的美麗瞬間，作品運用自然材質，以二種不同的造型表現不同花火般的造型與形象，可讓觀者穿梭其中，用不同的角度來感受不一樣的蜂炮火花。',
    engDescription: 'As Beehive Firecrackers is the most famous activity in Yanshui, artists represented this popular event in another form. As the firecrackers lit up at night, it blossomed in the sky. Through two different shapes and color to symbolize the blossoms booming in the air. Audience is welcomed to shuttle in between to view the work in different perspective.',
    coordinate: {
      latitude: 23.19066,
      longitude: 120.16167
    },
    image: require('../assets/images/27.png'),
  },
  {
    id: '28',
    title: '文化之塔 – 八',
    engTitle: 'Tower of Cultures "Ⅷ"',
    school: '京都造形藝術大學',
    engSchool: 'Kyoto University of Art & Design',
    instructor: '森岡 厚次',
    engInstructor: 'MORIOKA Koji',
    artist: '坪倉 有之介、山崎 匠、井上 沙紀、岩崎 玲奈、赤澤 美里',
    engArtist: 'TSUBOKURA Yunosuke, YAMAZAKI  Takumi, INOUE  Saki, IWASAKI  Reina, AKAZAWA Misato',
    description: '這座塔在底部展開，與“八“的漢字相似，八是東亞的幸運數字。這座塔代表了迄今為止建立起來的日本與台灣之間的關係，在不同區塊的八方塔表面呈現著兩方文化的傳統圖紋，這象徵著兩方的文化。這個作品傳達了“文化的相遇”。而其他空白的部分代表了我們希望未來有新的文化交流的可能。',
    engDescription: 'This tower spreads out at the base and is similar to the Chinese character for the number eight. Eight is a lucky number in East Asia. The tower represents the relationship between Japan and Taiwan that has been built up to now, and some traditional patterns of both countries are used on the surface in various places. This symbolizes both cultures. This work expresses the "encounter of cultures". And the other empty parts represent our hope for new encounters in the future.',
    coordinate: {
      latitude: 23.19060,
      longitude: 120.16185
    },
    image: require('../assets/images/28.png'),
  },
  {
    id: '29',
    title: '美味眼神',
    engTitle: 'Delicious Eyes',
    school: '台南應用科技大學美術系',
    engSchool: 'Tainan University of Technology',
    instructor: '黃金福',
    engInstructor: 'Huang Chin Fu',
    artist: '美食圖像原創：鍾宜紋；執行團隊：鍾宜紋、陳怡璇、柯衍吉、黃德馨、吳炘誼',
    engArtist: 'Chung Yi Wen; Chung Yi Wen, Chen I Hsuan, Ko Yen Ji, Huang De Xin Wu Xin Yi',
    description: '長期以來台南地區都是以「台南小吃」聞名於世，如果能將在地美食文化傳統發揚傳播，運用創意繪畫思維來推廣與「再創造」出台南美食的真實內涵與品質之美，這將是未來可期許之美食視覺文創產業。在此次參展作品「美味眼神」中，我們設計出12種台南較富盛名的美食形象：1.家族團圓辦桌 2.喜宴流水席 3.傳統魚市場 4.香腸豬肉攤 5.官田菱角 6.爆炒鱔魚 7.七股鮮蚵 8.白河蓮蓬 9.本產牛肉湯 10.關廟鳳梨與玉井芒果 11.鹽水鹽地柑仔蜜12.鹽水意麵。',
    engDescription: 'For a long time, Tainan is famous for its "Tainan snacks." If we can spread the tradition of local cuisine culture, and promote to the true tasty and quality of Tainan cuisine, it will be The future creative industries of food culture. In this exhibition, "Delicious Eyes", we have designed 12 famous Tainan food image: 1. Family reunion catering 2. Wedding  outdoor party 3. Traditional fish market 4. Sausage pork stalls 5. Guantian water chestnut 6 Fried eel 7. Qigu oyster 8. Baihe Lotus 9. Local beef soup 10. Guanmiao pineapple and Yujing mango 11. Yanshui salt tomato  12. Yanshui  pasta.',
    coordinate: {
      latitude: 23.19059,
      longitude: 120.16199
    },
    image: require('../assets/images/29.png'),
  },
  {
    id: '30',
    title: '花開祥雲',
    engTitle: 'Flowers bloom with auspicious cloud',
    school: '正修科技大學時尚生活創意設計系',
    engSchool: 'The Department of Modern Living and Creative Design,Cheng Shiu University',
    instructor: '蘇小夢',
    engInstructor: 'Su Hsiao Meng',
    artist: '呂思穎、張慈芳、李芊穆、林廣秦',
    engArtist: 'Lu Si Ying, Chang Tzu Fang, Li Chien Mu, Lin Guang Qin',
    description: '利用搭設在水面上的木製平台，搭設許多色環保再利用材質製作而成大大小小的花朵。結合其他含苞待放、亦或是燦爛盛開的花朵及金屬花梗，營造拱橋旁的美麗風景，並帶出臺南鹽水豐厚的歷史人文背景與月津港周邊的優質環境。\n本作品由正修科技大學時尚生活創意設計系蘇小夢老師帶領學生全程參與。',
    engDescription: 'Using recycling material to make colorful flowers on the wooden pedestal. With the main theme – rainbow flowers – are integrated to develop an arch bridge view. Let people discover the historical and beautiful scenery of Yanshuei in Tainan. \nThis work is made by Hsiao-Meng Su, assistant professor of department of Modern Living and Creative Design of Cheng-Shiu University with her students.',
    coordinate: {
      latitude: 23.19070,
      longitude: 120.16197
    },
    image: require('../assets/images/30.png'),
  },
  {
    id: '31',
    title: '曖曖內含光',
    engTitle: 'InnerGlow',
    school: '成功大學科技藝術碩士學位學程',
    engSchool: 'Techno Art, National Cheng Kung University',
    instructor: '林軒丞、陳明惠',
    engInstructor: 'Lin Hsuan Cheng, Chen Ming Hui',
    artist: '蔡政宏、陳亭臻、張芷誼、林佩昕',
    engArtist: 'Tsai Cheng Hung, Chen Ting Chen, Chang Chih Yi, Lin Pei Hsin',
    description: '星星對月津港的記憶是什麼？\n古詩「聚波漁火」形容月津港鼎盛時期夜間河港上滿滿漁火與滿天星斗交織，這大概就是星星記憶中的月津港吧？\n我們以抽象的星星模擬樣貌，並在裝置中加入具互動性的燈光裝置，試圖讓您能以星星的視角，回憶月津港的風華絕代。',
    engDescription: 'What is the memory about stars to Yuejingang? \nAn ancient poetry describes all the sparkling lights from fishing boats mingled with all stars at night in Yuejingang’s heyday. \nWould it be the memory about stars to Yuejingang? \nWe use light device on the exhibit to simulate the starry night so that you can see the prosperity of Yuejingang through the star.',
    coordinate: {
      latitude: 23.19069,
      longitude: 120.16210
    },
    image: require('../assets/images/31.png'),
  },
  {
    id: '32',
    title: '飄盪種籽',
    engTitle: 'The Drifting Seeds',
    school: '南華大學視覺藝術與設計系',
    engSchool: 'Graduate Institute and Department of Visual and Media Arts, Nanhua University',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '連敏盛、楊定遠、吳東晉、周穎、王子佳、林家誼',
    engArtist: 'Lian Min Sheng, Yang Ding Yuan, Wu Dong Jin, Zhou Ying, Wang Zi Jia, Lin Jia Yi',
    description: '外出的遊子，如同飄盪的種籽，來到這座城鎮收集資料的時候，在地領隊說了一句 『還居住在這座城鎮的同學，只剩下我而已』，或許許多鄉鎮都有著相同的問題，為了生存必須遠離自己熟悉的地方，長年在外生活而家鄉卻變得陌生，飄盪的人們 起身離開後才更能懂得家的樣子，離開或許才會是離家最近的距離。作品運用大量網狀編織的材質，試圖在空中與風產生互動，如同鄉愁那是一種你知道它存在，但卻無法具體敘述的物件，輕飄飄不穩定的搖盪在眼前，希望透過作品的連結將那種不可言喻的情緒表現出來。',
    engDescription: '“Among the fellows growing up together in this town, I am the only one who still resides here,” said the local tour guide. \nThe drifting seeds were just like the young generation of this old town, leaving their motherland for survival and better opportunity. The truth was the tour guide wasn’t the only one expressing the sadness toward his hometown. In fact, many cities and towns in Taiwan shared the similar issues, outflow of young people. On the other hand, although people were not familiar with their own origins after years of working in other places, they thought of them all the time. Maybe this emotion of being homesick shortened the distance between the migrants and homeland. Thus, artists were trying to make the artwork connect with the unexpressive emotion by the floating seeds.',
    coordinate: {
      latitude: 23.19078,
      longitude: 120.16204
    },
    image: require('../assets/images/32.png'),
  },
  {
    id: '33',
    title: '月津‧光蟲祭',
    engTitle: 'Moonlight ‧ Light Bug Festival',
    school: '國立臺南藝術大學',
    engSchool: 'Tainan National University of the Arts',
    instructor: '黃猷欽',
    engInstructor: 'Huang Yu Qin',
    artist: '陳雋中、辛綺、鍾佳橞',
    engArtist: 'CCChen, Kiki Shin, Chung Chia Hui',
    description: '「光蟲」是僅有在月津港燈節期間才會出現的一種神秘生物。\n以月津港燈節的作品燈光為食，用當地自然生態或奇幻的昆蟲和動植物的姿態出現。\n牠們將光芒儲存於腹部的透明瓶罐容器中，千變萬化、五顏六色；也會影響周遭的環境，將光儲存在花朵、菌菇、香蕉樹上，因而誕生了光之生態圈。',
    engDescription: '“Light Bug” is a mysterious creature that only appears during the Lunar New Year.  \nThe food of them is the light of “YUEJIN LANTERN  FESTIVAL”.\n“Light Bug” emerges with the gesture of local natural ecology or fantastic insects ,plants and animals. \nThey store the light in a transparent container on the abdomen. Ever-changing, colorful; will also affect the surrounding environment, the light stored in flowers, mushrooms, banana trees, and thus the birth of the eco-light.',
    coordinate: {
      latitude: 23.19085,
      longitude: 120.16192
    },
    image: require('../assets/images/33.png'),
  },
  {
    id: '34',
    title: '寄居蟹',
    engTitle: 'Hermit Crab',
    school: '崑山科技大學',
    engSchool: 'Kun Shan University',
    instructor: '王俊淵',
    engInstructor: 'Wang Jun Yuan',
    artist: '王俊淵、黃秀桂、劉哲廷、邱于庭',
    engArtist: 'Wang Jun Yuan, Huang Xiu Gui, Liu Zhe Ting, Qiu Yu Ting',
    description: '台灣早期的居民多數從中國移民而來，只為了找尋一處幸福的居所，好比寄居蟹找尋自己最舒適的家，我們在這裡做了一個最美麗的家，歡迎大家住進來。',
    engDescription: 'In the early times, most of people came from China and they were seeking for a good place to live in Taiwan. This is the same as a hermit crab always looks for the most comfortable home for itself. Creators would like to make the most beautiful artwork as a hermit crab’s home and welcome everyone come into this artwork and be a part of this artwork.',
    coordinate: {
      latitude: 23.19087,
      longitude: 120.16219
    },
    image: require('../assets/images/34.png'),
  },
  {
    id: '35',
    title: '落雨聲',
    engTitle: 'The Sound of Rainfall',
    school: '南華大學視覺藝術與設計系',
    engSchool: 'Graduate Institute and Department of Visual and Media Arts, Nanhua University',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '莊濰孺、林宣妤、朱育箴',
    engArtist: 'Zhuang Wei Ru, Lin Xuan Yu, Zhu Yu Zhen',
    description: '創作的概念來自於對於自然循環的讚嘆，地球上有百分之七十皆為水資源，在經由自然環境中演變成各式樣貌，從冰河，河川，海洋，地下水層...等不同的形態，在此透過作品的型式表現一種依水而來，伴水而生，從哪兒來又回到那兒去，期待月津港或許隨著時代的變遷，會逐漸喪失其不同以往的功能性，但卻可以在自然狀況的循環下也找出屬於適合自己的新型態，再度發光發熱，重現風華萬象。',
    engDescription: 'The original idea was to praise the miracle of natural cycle. Approximately 70 % of Earth surface is covered with water which is stored in various forms, including glacier, river, ocean, underground water, etc. While water is such an important element of Earth, human civilization developed along the water source. The prosperity of Yuejin harbor was also resulted from the water. Although Yuejin harbor lost its original purpose, artists expected it would like the cycle of the nature, finding its way and succeeding again.',
    coordinate: {
      latitude: 23.19094,
      longitude: 120.16211
    },
    image: require('../assets/images/35.png'),
  },
  {
    id: '36',
    title: '月津呢喃',
    engTitle: 'The Whisper of Yuejin',
    school: '南臺科技大學視覺傳達設計系',
    engSchool: 'Visual Communication Design Department, Southern Taiwan University of Science and Technology',
    instructor: '徐垂文',
    engInstructor: 'Hsu Chui Wen',
    artist: '曾子毓',
    engArtist: 'Tseng Tzu Yu',
    description: '作品以對話為主要設計概念。月津港親水公園給人一種溫馨悠閒的氛圍，而鹽水地區古時也因有月津港而繁榮，依水生長的城鎮，彎月般的造型如同母親的臂膀守護著這個城鎮，想像如果這條河會說話，那她又會低語些什麼，作品中運用大量現代科技的溝通方式(對話框)，如同月津港在對來此地參觀或居住的民眾打招呼一般，溫柔而親近低聲的呢喃著歡迎光臨。',
    engDescription: 'Adopting the dialog of daily conversation, it depicted the relaxing and welcomed atmosphere of Yuejingang Riverside Park. The curved shaped of Yuejin harbor symbolized Mother’s protective arms, guarding the entire region and cultivating the prosperity. Imagine if the meandering river talks, what she would whisper to us? Thus, to represent the hospitality of the residents, the work adopted technology, visualizing the common Taiwanese greeting into dialogue bubbles.',
    coordinate: {
      latitude: 23.19101,
      longitude: 120.16213
    },
    image: require('../assets/images/36.png'),
  },
  {
    id: '37',
    title: '太空人計畫',
    engTitle: 'The Astronaut’s Plan',
    school: '南華大學創意產品設計學系碩士班',
    engSchool: 'Department of Creative Product Design, Nanhua University',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '呂裕文、黃微橙',
    engArtist: 'Lu Yu Wen, Huang Wei Cheng',
    description: '鹽水小鎮以蜂炮著名，現為全球十大特殊慶典之一，在國際上替台灣發光發熱，而這樣的特殊文化傳承了數百年，代表著居民的一種堅定的信仰，本作品將蜂炮的元素放大加入趣味性的太空人造型，意味著蜂炮活動充滿冒險開拓的精神，希望可以用不同的方式介紹當地特殊的文化。',
    engDescription: 'Beehive Firecrackers, one of the most unique rituals in the world, is the most representative association with Yanshui. As this ritual not only enjoyed its worldwide reputation, but also expressed the firm and sincere belief of the locals, artist adopted the element of Beehive Firecrackers into his work, adding the entertaining astronauts. While the astronauts launched their adventure and rocketed into the sky, it unveiled of this exclusive activity.',
    coordinate: {
      latitude: 23.19111,
      longitude: 120.16213
    },
    image: require('../assets/images/37.png'),
  },
  {
    id: '38',
    title: '飛行的意義',
    engTitle: 'The Purpose of Flying',
    school: '國立雲林科技大學創意生活設計系',
    engSchool: 'Department of Creative Design, National Yunlin University of Science and Technology',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '蔡立婷',
    engArtist: 'Tsai Li Ting',
    description: '作品運用舊式飛行船為主體，並在下方改造其乘載的空間，轉化為一艘船的造型，除了表現月津港原始具有商港的功能性外，也在上方製造微型城鎮，如同現今鹽水的現狀，夢想要起飛回復再現往日風華，乘載的卻是生活與現實的重擔，該如何找出相對的選擇，落在你我對於它的想像，與想給予它的意義。',
    engDescription: 'By using the idea of the blimp, artist reflected the heavy challenge of current Yanshui, transformation. The gondola was transformed into a boat carrying the village, flying toward the unknown future which was resulted from the struggles of the locals who yearned for the answers of bringing back the splendor that once succeeded in the town and hoped to boost the honor of the harbor again. However, this blimp of hopes and wishes also loaded with the burden of reality and survival. Finding a correct answer and future for Yanshui lies on our imagination and definition toward it.',
    coordinate: {
      latitude: 23.19151,
      longitude: 120.16190
    },
    image: require('../assets/images/38.png'),
  },
  {
    id: '39',
    title: '月映',
    engTitle: 'The Reflection of Moon',
    school: '嘉義大學視覺藝術研究所',
    engSchool: 'The Department of Visual Art,  National Chiayi University',
    instructor: '戴明德',
    engInstructor: 'Dai Ming De',
    artist: '朱大維',
    engArtist: 'Zhu Da Wei',
    description: '鹽水古名為月津，因為倒風內海而成為貿易繁榮的港口城鎮，而港口造型又有如月亮一般因而得名。作品使用月亮的意象，以半月的造型，搭配月津港燈節獨特的水上燈節形式，運用倒影將作品完整表現出來，也透過這樣的創作方式去敘述此地依水而生的歷史沿革。材質上選擇使用竹材為主要材質，透過竹子樸質的感受與漸變色系的特質，來讓民眾感受這樸質卻充滿變化的歷史小鎮。',
    engDescription: 'Yanshui was once named as Yuejin since its curved geographic structure seemed like a moon shape. Due to this special geographic setting, it brought prosperous trades in this town. To recall people’s memory of Yanshui’s history, the artist created this massive balsamic moon which half formed from the reflection from the water to represent the name of the harbor and glory of its story. Besides, the choice of the material also presented artist’s ingenuity.  First, he varied the types of bamboo to create the layers of the color to explain the change of the Yanshui. Then as bamboo was one of the common materials in the past, it also indicated the simplicity of this cultural town.',
    coordinate: {
      latitude: 23.19161,
      longitude: 120.16194
    },
    image: require('../assets/images/39.png'),
  },
  {
    id: '40',
    title: '月津星',
    engTitle: 'Star of Yue-Jin',
    school: '國立台北藝術大學 x 國立台灣大學',
    engSchool: 'Taipei National University of the Arts x National Taiwan University',
    instructor: '張乃文',
    engInstructor: 'Chang Nai Wen',
    artist: '周學涵、姜名駿、陳重源',
    engArtist: 'Chou Hsueh Han, Chiang Ming Chun, Chen Chung Yuan',
    description: '在一個河港有如彎月般的月津港，我們創造屬於這裡的星星。以星星作為載體，將月津的影像透過訊號的轉換，映像(mapping)成為有機的光之效果。',
    engDescription: 'At the crescent shaped Yue-Jin harbor, we create a star as the medium to show the beauty of Yue-Jin. The organic light effects are derived from the image of this scene.',
    coordinate: {
      latitude: 23.19162,
      longitude: 120.16189
    },
    image: require('../assets/images/40.png'),
  },
  {
    id: '41',
    title: '月光津影',
    engTitle: 'Retro Memory',
    school: '成功大學科技藝術碩士學位學程',
    engSchool: 'Techno Art, National Cheng Kung University',
    instructor: '林軒丞、陳明惠',
    engInstructor: 'Lin Hsuan Cheng, Chen Ming Hui',
    artist: '王乙如、潘冠源、張虔祥、魯岱瑄、王柏涵',
    engArtist: 'Wang Yi Ju, Pan Guan Yuan, Jhang Cian Siang, Lu Dai Syuan, Wang Bo Han',
    description: '四種傳統風格線條組成的圖案，四大主題分別代表當地特色 : 月津港、橋南老街、八角樓、鹽水蜂炮。\n以投射方式，利用影子與光線在地上呈現作品，讓賞客可以從中穿梭。',
    engDescription: 'Four icons composed of stylish lines refering to the traditional symbols. Four topics represent different cultural landscapes: Yuejin port, Ciaonan old street, Bajiao building and Yanshui beehive fireworks festival.\nProjecting spotlight on the ground, we present our art work as the remix of shadow and light. Visitors were invited to join in, or even become part of the light pattern.',
    coordinate: {
      latitude: 23.19159,
      longitude: 120.16180
    },
    image: require('../assets/images/41.png'),
  },
  {
    id: '42',
    title: '遞變',
    engTitle: 'Morphological gradient',
    school: '正修科技大學建築與室內設計系',
    engSchool: 'Department of Architecture and Interior Design, Cheng Shiu University',
    instructor: '倪順成',
    engInstructor: 'Ni Shun Chen',
    artist: '李聖揚、王宇千、盧冠宇',
    engArtist: 'Lee Sheng Yang, Wang Yu Chien, Lu Guan Yu',
    description: '作品主題為「遞變」，隱喻著環境與時代的快速變化，省思對於自然的愛惜。作品之構思即是以橋的行進過程作為思考的出發點，設計採用木框的方式循序旋轉排列，創造出層層漩渦遞變的效果，亦有水中隧道的感覺，期待觀看者不僅在橋上有視覺上的享受，在彼岸一樣能有橫向跨越河流的不同感受。此外框上燈光加上緩慢節奏、漸層，顏色採用白光，讓框的空間顯現延伸感，凸顯遞變的感覺。',
    engDescription: 'The subject of the work is " Morphological gradient ", a metaphor for rapid changes in the environment and the times, reflection on “love nature”. The idea of the work is process of the bridge. The use of wooden frame sequential rotation arrangement, to create of swirling effect and water tunnel feeling. Expect the viewer not only to have a visual enjoyment on the bridge, but also to have the same feeling on the shore. In addition, the light gradient is also the design focus. Let the frame space show a sense of morphological gradient.',
    coordinate: {
      latitude: 23.19168,
      longitude: 120.16180
    },
    image: require('../assets/images/42.png'),
  },
  {
    id: '43',
    title: '星月許願',
    engTitle: 'Make a Moon Wish',
    school: '國立台南藝術大學',
    engSchool: 'Tainan National University of the Arts (TNNUA)',
    instructor: '潘正育',
    engInstructor: 'Pan Cheng Yu',
    artist: '尹子潔、黃詩芸',
    engArtist: 'Yin Zi Jie, Huang Shi Yun',
    description: '驅車南下的夜晚，常會看見無數矩形陣列的小光點，照亮廣袤黝黑的夜間田野，原來是「電照菊」的栽培地：閃閃發光彷彿地上的星星般，輝耀著豐收之美。月津港的月河倒映著天空，運用湖面倒映的特性，製造出另一平面的錯覺，「水中星空」在流星絢麗劃過之際，使天地顛倒。白日觀菊、夜晚賞燈，新的一年，一起向星月許願吧!',
    engDescription: 'Driving down south in late night, we often see these little lights that are well-organized in perfect squares, glittering the whole dark, vast field: the growing area of chrysanthemum. The famous artificial lights shining in the night like stars on the ground, blooming with the beauty of harvest. Moon river of Yuejin Port creates an illusion of another surface with the reflection of sky onto the lake. When the shooting star passed by, “star in the water” also swung across, turning the world upside down. Watching chrysanthemum with a morning sun and the glittering lights in the night, let’s make a wish to the moon and the stars as the brand new year comes!',
    coordinate: {
      latitude: 23.19183,
      longitude: 120.16169
    },
    image: require('../assets/images/43.png'),
  },
  {
    id: '44',
    title: '靈光閃閃',
    engTitle: 'The spark of inspiration',
    school: '南榮科技大學創意產品設計系',
    engSchool: 'The Department of Creative Product Design, Nan Jeon University of Science and Technology',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '黎淑祺、于佩吟、孫偉誠、張鈺賢',
    engArtist: 'Li Shu Chi, Yu Pei Yin, Sun Wei Cheng, Chang Yu Hsien',
    description: '作品以群聚與水生為主要概念出發，運用水母飄逸悠遊的特質，表現月津港優閒自在的感覺，白天透過透明材質與光線折射效果製造閃亮動人的視覺性，而夜晚則加入螢光漆料製造另外一種夢幻般的視覺效果，如同燈會帶給月津港的魅力。',
    engDescription: 'When a cluster of jellyfish swimming and drifting in the water, it always gives a feeling of relaxation which is exactly the atmosphere that exists in Yuejin harbor. Through the transparent material and fluorescent paint, the artwork created two different sensations in the day and at night, adding the charisma to the lantern festival of Yuejin.',
    coordinate: {
      latitude: 23.19190,
      longitude: 120.16176
    },
    image: require('../assets/images/44.png'),
  },
  {
    id: '45',
    title: '日穿山水',
    engTitle: 'The landscape',
    school: '嘉義大學視覺藝術研究所',
    engSchool: 'The Department of Visual Art,  National Chiayi University',
    instructor: '戴明德',
    engInstructor: 'Dai Ming De',
    artist: '鍾佳衛',
    engArtist: 'Zhong Jia Wei',
    description: '作品以穿越為概念出發，描寫一種以自然而生的山水景觀，運用水墨留白的概念將山陵的線條框架在空間中勾勒出來，並與水面相互輝映。簡約的線條與留白的面積就好像月津港的繁華散去後留下詩意的淒美感。',
    engDescription: 'The lines of this creation represented the philosophy of white space which was often seen and applied in Chinese painting. The combination of the lines depicted the landscape of mountains which corresponded with the water. Artist tried to imply the beauty of simplicity that the prosperity left behind.',
    coordinate: {
      latitude: 23.19200,
      longitude: 120.16216
    },
    image: require('../assets/images/45.png'),
  },
  {
    id: '46',
    title: 'HOME 魚',
    engTitle: 'Home Fish / manta',
    school: '南榮科技大學創意產品設計系',
    engSchool: 'The Department of Creative Product Design, Nan Jeon University of Science and Technology',
    instructor: '陳禹廷',
    engInstructor: 'Chen Yu Ting',
    artist: '陳羿忻、陳平翊、王慧敏、劉鄭華、鄭宇哲',
    engArtist: 'Chen Yi Xin, Chen Ping Yi, Wang Hui Min, Liu Zheng Hua, Zheng Yu Zhe',
    description: '作品以魟魚群聚為設計概念，魟魚具有一特殊群聚的特質，如同人類生活產生聚落。設計取其諧音將魟魚轉化成英文Home，代表著鹽水月津港如帶給人如同家一般的感受，歡迎大家回家來到此地享受在地充滿人情味的特質。',
    engDescription: 'The artwork was inspired by the characteristics of manta. Like human beings, mantas are social animals and live in groups. As Chinese pronunciation of manta pronounce as Hōng yú, sounding like home fish, artists used the marine species to portray Yuejin harbor as the home of the fish, as well as the motherland of her people.',
    coordinate: {
      latitude: 23.19198,
      longitude: 120.16225
    },
    image: require('../assets/images/46.png'),
  },
  {
    id: '47',
    title: '炮兒-Power',
    engTitle: 'Power',
    school: '崑山科技大學、南榮科技大學、明道大學',
    engSchool: 'Kun Shan University, Nan Jeon University, MingDao University',
    instructor: '王俊淵',
    engInstructor: 'Wang Jun Yuan',
    artist: '王俊淵、楊裕閔、柯尚廷、李志豪、歐仕銓',
    engArtist: 'Wang Jun Yuan, Yang Yu Min, Ke Shang Ting, Li Zhi Haom Ou Shi Quan',
    description: '以炮城的概念來進行創作，結合舉重選手的動作，將蜂炮與力量（Power）巧妙的聯結在一起。本作品是以台灣2017年在世大運優秀的表現做為主題，讓民眾再次迴響對台灣的驕傲。',
    engDescription: 'Using the concept of artillery in the creation and combined with the action of weightlifter, have the idea of beehive firecrackers and power connected. Also, this artwork is based on the excellent performance of Taiwan Universiade in 2017 which represents the honor and glory of our country.',
    coordinate: {
      latitude: 23.19198,
      longitude: 120.16263
    },
    image: require('../assets/images/47.png'),
  },
  {
    id: '48',
    title: '浮光‧水影',
    engTitle: 'Aqua Mira',
    school: '',
    engSchool: '',
    instructor: '',
    engInstructor: '',
    artist: 'The Technical Direction Company of Australia Pty Ltd, STYLE ADVERTISING COMMUNICATION LTD of Taiwan',
    engArtist: '',
    description: '如歌 如夢 如畫 故事的腳本 全在心念之間\n展演時段(每日)：19:30 / 20:00 / 20:30 / 21:00 / 21:30 / 22:00\n展演時間：約 4 分鐘',
    engDescription: 'A vivid mirage, a world beyond imagination.\nDaily Schedule: 19:30 / 20:00 / 20:30 / 21:00 / 21:30 / 22:00\nDuration: approximately 4 minutes',
    coordinate: {
      latitude: 23.19201,
      longitude: 120.16259
    },
    image: require('../assets/images/48.png'),
  },
]